<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ec70ee19-4279-4051-8aa4-380f6fc9ec04</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
	  <NoWarn>$(NoWarn);1591</NoWarn>
	  <DockerfileContext>..\..\..</DockerfileContext>
	  <DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\InnoClinic.Shared.csproj" />
    <ProjectReference Include="..\Appointments.API.Infrastructure\InnoClinic.Appointments.API.Infrastructure.csproj" />
  </ItemGroup>
	
	<ItemGroup>
		<InternalsVisibleTo Include="Appointments.API.Tests" />
	</ItemGroup>

</Project>
