<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" />
    <PackageReference Include="BCrypt" />
    <PackageReference Include="BCrypt.Net-Next" />
	<PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\InnoClinic.Shared.csproj" />
    <ProjectReference Include="..\Auth.API.DAL\InnoClinic.Auth.API.DAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="BllMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>BllMessages.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="BllMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>BllMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
