//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnoClinic.Appointments.API.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppointmentsApiMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppointmentsApiMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InnoClinic.Appointments.API.Application.AppointmentsApiMessages", typeof(AppointmentsApiMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment time must be between {0} and {1}.
        /// </summary>
        public static string AppointmentBetweenMessage {
            get {
                return ResourceManager.GetString("AppointmentBetweenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment date cannot be in the past.
        /// </summary>
        public static string AppointmentInPastMessage {
            get {
                return ResourceManager.GetString("AppointmentInPastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only appointments that aren&apos;t approved can be rescheduled..
        /// </summary>
        public static string CannotBeRescheduledMessage {
            get {
                return ResourceManager.GetString("CannotBeRescheduledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaints are required.
        /// </summary>
        public static string ComplaintsRequiredMessage {
            get {
                return ResourceManager.GetString("ComplaintsRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conclusion is required.
        /// </summary>
        public static string ConclusionIsRequiredMessage {
            get {
                return ResourceManager.GetString("ConclusionIsRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected doctor does not match the specified specialization or office.
        /// </summary>
        public static string DoctorDoesNotMatchMessage {
            get {
                return ResourceManager.GetString("DoctorDoesNotMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected doctor is not available.
        /// </summary>
        public static string DoctorNotAvailableMessage {
            get {
                return ResourceManager.GetString("DoctorNotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have access to this resource.
        /// </summary>
        public static string ForbiddenAccessMessage {
            get {
                return ResourceManager.GetString("ForbiddenAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not active or not available..
        /// </summary>
        public static string InactiveEntityMessage {
            get {
                return ResourceManager.GetString("InactiveEntityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesn&apos;t exist..
        /// </summary>
        public static string NotFoundMessage {
            get {
                return ResourceManager.GetString("NotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This time is already taken by another patient..
        /// </summary>
        public static string OverlappingAppointmentMessage {
            get {
                return ResourceManager.GetString("OverlappingAppointmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations are required.
        /// </summary>
        public static string RecommendationsAreRequiredMessage {
            get {
                return ResourceManager.GetString("RecommendationsAreRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This appointment already has a result..
        /// </summary>
        public static string ResultAlreadyExists {
            get {
                return ResourceManager.GetString("ResultAlreadyExists", resourceCulture);
            }
        }
    }
}
